
INSERT INTO productos (nombre, descripcion, precio, imagen_url) VALUES
('Huevos (docena)', 'Docena de huevos frescos de granja', 2.50, 'https://example.com/huevos.jpg'),
('Leche (litro)', 'Leche entera pasteurizada', 1.20, 'https://example.com/leche.jpg'),
('Pan de molde', 'Pan de molde blanco fresco', 1.80, 'https://example.com/pan.jpg'),
('Arroz (kilo)', 'Arroz blanco de grano largo', 1.50, 'https://example.com/arroz.jpg'),
('Frijoles negros (lata)', 'Frijoles negros listos para comer', 0.90, 'https://example.com/frijoles.jpg'),
('Aceite vegetal (litro)', 'Aceite de girasol para cocinar', 3.00, 'https://example.com/aceite.jpg'),
('Azúcar (kilo)', 'Azúcar blanca refinada', 1.10, 'https://example.com/azucar.jpg'),
('Sal (kilo)', 'Sal de mesa yodada', 0.80, 'https://example.com/sal.jpg'),
('Café molido (250g)', 'Café molido para cafetera', 4.50, 'https://example.com/cafe.jpg'),
('Jabón de baño', 'Barra de jabón para el cuerpo', 0.75, 'https://example.com/jabon.jpg'),
('Shampoo (500ml)', 'Shampoo para todo tipo de cabello', 3.50, 'https://example.com/shampoo.jpg'),
('Papel higiénico (4 rollos)', 'Papel higiénico suave de doble hoja', 2.00, 'https://example.com/papel_higienico.jpg'),
('Refresco de cola (2 litros)', 'Bebida gaseosa sabor cola', 2.20, 'https://example.com/refresco.jpg'),
('Agua embotellada (1.5 litros)', 'Agua mineral sin gas', 1.00, 'https://example.com/agua.jpg'),
('Galletas saladas (paquete)', 'Galletas para botanear', 1.30, 'https://example.com/galletas.jpg'),
('Papas fritas (bolsa)', 'Papas fritas con sal', 1.50, 'https://example.com/papas_fritas.jpg'),
('Cebolla (kilo)', 'Cebolla blanca fresca', 1.00, 'https://example.com/cebolla.jpg'),
('Tomate (kilo)', 'Tomate rojo para ensalada', 1.20, 'https://example.com/tomate.jpg'),
('Papas (kilo)', 'Papas para cocinar', 0.90, 'https://example.com/papas.jpg'),
('Limones (kilo)', 'Limones jugosos', 1.50, 'https://example.com/limones.jpg'),
('Manzanas (kilo)', 'Manzanas rojas frescas', 2.00, 'https://example.com/manzanas.jpg'),
('Plátanos (kilo)', 'Plátanos frescos', 1.30, 'https://example.com/platanos.jpg'),
('Pechuga de pollo (kilo)', 'Pechuga de pollo fresca sin hueso', 7.00, 'https://example.com/pollo.jpg'),
('Carne molida (kilo)', 'Carne de res molida', 8.50, 'https://example.com/carne.jpg'),
('Queso fresco (250g)', 'Queso blanco fresco', 2.80, 'https://example.com/queso.jpg'),
('Jamón de pavo (200g)', 'Rebanadas de jamón de pavo', 3.20, 'https://example.com/jamon.jpg'),
('Yogurt natural (litro)', 'Yogurt natural sin azúcar', 2.50, 'https://example.com/yogurt.jpg'),
('Cereal de maíz (caja)', 'Hojuelas de maíz para el desayuno', 3.80, 'https://example.com/cereal.jpg'),
('Atún en lata', 'Lata de atún en aceite', 1.50, 'https://example.com/atun.jpg'),
('Sopa de fideos (sobre)', 'Sopa instantánea de fideos', 0.60, 'https://example.com/sopa.jpg'),
('Pasta (spaghetti 500g)', 'Pasta de sémola de trigo', 1.20, 'https://example.com/pasta.jpg'),
('Salsa de tomate (lata)', 'Salsa de tomate para pasta', 1.00, 'https://example.com/salsa_tomate.jpg'),
('Mayonesa (frasco)', 'Mayonesa clásica', 2.30, 'https://example.com/mayonesa.jpg'),
('Mostaza (frasco)', 'Mostaza americana', 1.90, 'https://example.com/mostaza.jpg'),
('Ketchup (botella)', 'Salsa de tomate Ketchup', 2.10, 'https://example.com/ketchup.jpg'),
('Servilletas (paquete)', 'Paquete de servilletas de papel', 1.00, 'https://example.com/servilletas.jpg'),
('Detergente en polvo (kilo)', 'Detergente para ropa', 4.00, 'https://example.com/detergente.jpg'),
('Blanqueador (litro)', 'Blanqueador para ropa', 1.50, 'https://example.com/blanqueador.jpg'),
('Bolsas de basura (rollo)', 'Rollo de bolsas para basura', 2.00, 'https://example.com/bolsas_basura.jpg'),
('Velas (paquete)', 'Paquete de 4 velas', 1.00, 'https://example.com/velas.jpg');
