# Configuración para la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/tiendabarrio
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cuando la aplicación inicie, Spring Boot intentará actualizar el esquema de la BD si hay cambios
spring.jpa.hibernate.ddl-auto=update

# Dialecto de MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
